const mongoose = require('mongoose');

const htxManagementRecordSchema = new mongoose.Schema({
  module: {
    type: String,
    enum: [
      'documents',
      'tasks',
      'finance',
      'partners',
      'training',
      'technical-guidance',
      'technical-training',
      'pest-control',
      'product-inspections',
      'nonconformities',
      'material-supervision',
      'technical-proposals',
      'technical-reports',
      'distribution-orders',
      'distribution-shipments',
      'market-development',
      'customer-feedback',
      'product-finalization',
      'distribution-finance-requests',
      'accounting-transactions',
      'accounting-receivables',
      'accounting-payables',
      'accounting-reports',
      'tax-obligations',
      'financial-recommendations',
      'farmer-reports',
      'farmer-suggestions',
      'farmer-equipment-requests',
      'farmer-duty-confirmations',
    ],
    required: true,
    index: true,
  },
  htxId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  title: { type: String, required: true, trim: true },
  code: { type: String, trim: true },
  description: { type: String, trim: true },
  status: { type: String, default: 'Draft', index: true },
  priority: { type: String, enum: ['Low', 'Medium', 'High', 'Urgent'], default: 'Medium' },
  amount: { type: Number, default: 0 },
  direction: { type: String, enum: ['Income', 'Expense', 'None'], default: 'None' },
  partnerName: { type: String, trim: true },
  assignedToName: { type: String, trim: true },
  assignedToRole: { type: String, trim: true },
  location: { type: String, trim: true },
  startDate: { type: Date },
  endDate: { type: Date },
  dueDate: { type: Date },
  documentType: { type: String, trim: true },
  tags: [{ type: String, trim: true }],
  farmerIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true }],
  metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
}, { timestamps: true });

htxManagementRecordSchema.index({ htxId: 1, module: 1, createdAt: -1 });
htxManagementRecordSchema.index({ htxId: 1, module: 1, status: 1 });

module.exports = mongoose.model('HtxManagementRecord', htxManagementRecordSchema);
