// Auth API endpoints
export const apiLogin = '/auth/login'
export const apiRegister = '/auth/register'
export const apiLogout = '/auth/logout'
export const apiGoogleLogin = '/auth/google'
export const apiForgotPassword = '/auth/forgot-password'
export const apiResetPassword = '/auth/reset-password'
export const apiForceChangePassword = '/auth/force-change-password'
export const apiChangePassword = '/auth/change-password'
export const apiGetProfile = '/auth/profile'
